repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --all --manifest-path src-tauri/Cargo.toml -- --check
        language: system
        pass_filenames: false
        files: ^src-tauri/.*\.rs$

      - id: svelte-check
        name: svelte-check
        entry: npm run check
        language: system
        pass_filenames: false
        files: ^(src/|package(-lock)?\.json|svelte\.config\.js|tsconfig\.json|vite\.config\.js)
